# Generated by Django 3.1.4 on 2020-12-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201221_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='category',
        ),
    ]
